_wandb:
    value:
        cli_version: 0.23.0
        e:
            qb5bag1sims7uz9qbxn1f8v1gju8etch:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "9663676416"
                codePath: rnn_learner.py
                codePathLocal: rnn_learner.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "994662584320"
                        used: "436900380672"
                email: ken.utm0200829@gmail.com
                executable: /Users/utsumikensuke/Research/Cartpole/.venv/bin/python
                git:
                    remote: https://github.com/ken0200829/Cartpole.git
                host: utsumikensukenoMacBook-Air.local
                memory:
                    total: "25769803776"
                os: macOS-26.1-arm64-arm-64bit
                program: /Users/utsumikensuke/Research/Cartpole/rnn_learner.py
                python: CPython 3.12.4
                root: /Users/utsumikensuke/Research/Cartpole
                startedAt: "2025-11-23T02:50:55.506794Z"
                writerId: qb5bag1sims7uz9qbxn1f8v1gju8etch
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 1
                - 2
                - 16
            "4": 3.12.4
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
batch_size:
    value: 64
dropout:
    value: 0.3
hidden_size:
    value: 64
learning_rate:
    value: 0.001
num_epochs:
    value: 50
num_layers:
    value: 2
patience:
    value: 10
sequence_length:
    value: 10
temperature:
    value: 1
use_attention:
    value: true
